#!/bin/bash

sleep 0.5

firefox &
code &
urxvt256c-ml &
urxvt256c-ml &
urxvt256c-ml &
urxvt256c-ml &
signal-desktop &
flatpak run com.discordapp.Discord &
~/.electron-apps/whats-app/whats-app &
/opt/Notable/notable &