#!/bin/bash

# Utility for maim as a screenshot/color picker tool

if [ $1 == "area" ]; then
  grim -g "$(slurp -w 0 -b 00000033)" - | wl-copy
elif [ $1 == "window" ]; then
  maim -l -b 0 -c 0,0,0,0.5 -st 9999999 -u | convert - \( +clone -background black -shadow 128x16+0+0 \) +swap -background none -layers merge +repage ~/Pictures/$(date +%s).png
elif [ $1 == "color" ]; then
  grim -g "$(slurp -p -b 00000000)" -t ppm - | convert - -format '#%[hex:u]' info:- | wl-copy
fi