#!/bin/bash

# Start services
sxhkd &
compton -b --config ~/.config/compton.conf &
polybar default &
~/.config/rofi/clipmenu/clipmenud &
redshift -t 5200:3200 -l 52.5200:13.405 &

# Setup config
source ~/.zshrc &
setxkbmap &
xrdb -merge ~/.Xresources &
xsetroot -cursor_name left_ptr &
feh --bg-scale ~/.wallpaper.jpg &

# Start applications
dropbox start &
syncthing -no-browser &

firefox &

code &

urxvt256c &
urxvt256c &
urxvt256c &
urxvt256c &

signal-desktop &
flatpak run com.discordapp.Discord &
~/.electron-apps/whats-app/whats-app &
