#!/bin/bash

# Start services
sxhkd &
compton -b --config ~/.config/compton.conf &
polybar default &
~/.config/rofi/clipmenu/clipmenud &
redshift -t 5500:3500 -l 52.5200:13.405 &

# Setup config
xrdb -merge ~/.Xresources &
xsetroot -cursor_name left_ptr &
razercfg  -r 3500 &
feh --bg-scale ~/.wallpaper.png &

# Start applications
dropbox start &

firefox &

code &

urxvt &
urxvt &
urxvt &
urxvt &

signal-desktop &
Discord &
~/.electron-apps/whats-app/whats-app &
