#!/bin/bash

# Basic bspwm config
bspc config border_width          0
bspc config window_gap            16
bspc config top_padding           32

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true
bspc config history_aware_focus   true
bspc config click_to_focus        true
bspc config focus_follows_pointer false

# Setup desktops
bspc monitor -d web dev term social misc
bspc desktop web -l monocle
bspc desktop dev -l monocle

# Application specific rules
bspc rule -a Firefox desktop=^1
bspc rule -a Code desktop=^2
bspc rule -a URxvt desktop=^3
bspc rule -a discord desktop=^4
bspc rule -a Signal desktop=^4
bspc rule -a whats-app-nativefier-d52542 desktop=^4
bspc rule -a TelegramDesktop desktop=^4
bspc rule -a Nautilus desktop=^5
bspc rule -a Peek state=floating

# Autostart
~/.config/bspwm/autostart &
