#!/bin/bash

# Utility for starting different launchers
# 
# Examples:
# ./launcher default    -->			Show the default rofi launcher in drun mode
# ./launcher clipmenu   -->			Show a rofi launcher in dmenu mode with clipmenu piped into it
# ./launcher gopass     -->			Show a rofi launcher in dmenu mode with gopass piped into it

if [ $1 == "clipmenu" ]; then
  ~/.config/rofi/clipmenu/clipmenu -p clipboard
elif [ $1 == "gopass" ]; then
  ~/dev/golang/bin/gopass ls --flat | rofi -dmenu -p gopass | xargs --no-run-if-empty ~/dev/golang/bin/gopass show -f | head -n 1 | xdotool type --clearmodifiers --file -
else
  rofi -plugin-path /usr/local/lib/rofi -show drun -no-show-match -no-sort -show-icons
fi