#!/bin/bash

# Utility for starting different launchers
# 
# Examples:
# ./launcher default    -->			Show the default rofi launcher in drun mode
# ./launcher clipmenu   -->			Show a rofi launcher in dmenu mode with clipmenu piped into it

if [ $1 == "clipmenu" ] ; then
  ~/.config/rofi/clipmenu/clipmenu -p clipboard
else 
  rofi -plugin-path /usr/local/lib/rofi -show drun -no-show-match -no-sort
fi