#!/bin/bash
letterEnteredColor=#d44956ff
letterRemovedColor=#d44956ff
passwordCorrect=#00000000
passwordIncorrect=#d44956ff
background=#00000000
foreground=#ffffffff

i3lock \
  -i "$HOME/.config/bspwm/lock.png" \
  --timestr="%H:%M" \
  --timepos="x+85:h-70" \
  --datepos="x+135:h-45" \
  --clock --datestr "Type password to unlock..." \
  --insidecolor=$background --ringcolor=$foreground --line-uses-inside \
  --keyhlcolor=$letterEnteredColor --bshlcolor=$letterRemovedColor --separatorcolor=$background \
  --insidevercolor=$passwordCorrect --insidewrongcolor=$passwordIncorrect \
  --ringvercolor=$foreground --ringwrongcolor=$foreground --indpos="x+270:h-68" \
  --radius=20 --ring-width=4 --veriftext="" --wrongtext="" --blur 4 \
  --verifcolor="$foreground" --timecolor="$foreground" --datecolor="$foreground" \
  --noinputtext="" --force-clock $lockargs
