#!/bin/bash

# Utility for volume control and a notification popup with dunst.
# 
# Examples:
# ./volume up       -->			Increase volume by 7
# ./volume down     -->			Decrease volume by 7
# ./volume mute     -->			Mute

function get_volume {
  amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
  amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
  volume=$(get_volume)

  if is_mute ; then
    bar="婢  Mute"
  elif [ $volume -eq 100 ]; then
    bar="墳  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  elif [ $volume -gt 98 ]; then
    bar="墳  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  elif [ $volume -gt 91 ]; then
    bar="墳  ━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  elif [ $volume -gt 84 ]; then
    bar="墳  ━━━━━━━━━━━━━━━━━━━━━━━━━"
  elif [ $volume -gt 77 ]; then
    bar="墳  ━━━━━━━━━━━━━━━━━━━━━━"
  elif [ $volume -gt 70 ]; then
    bar="墳  ━━━━━━━━━━━━━━━━━━━━"
  elif [ $volume -gt 63 ]; then
    bar="墳  ━━━━━━━━━━━━━━━━━━"
  elif [ $volume -gt 56 ]; then
    bar="墳  ━━━━━━━━━━━━━━━━━"
  elif [ $volume -gt 49 ]; then
    bar="奔  ━━━━━━━━━━━━━━━"
  elif [ $volume -gt 42 ]; then
    bar="奔  ━━━━━━━━━━━━━"
  elif [ $volume -gt 35 ]; then
    bar="奔  ━━━━━━━━━━━"
  elif [ $volume -gt 28 ]; then
    bar="奔  ━━━━━━━━━"
  elif [ $volume -gt 21 ]; then
    bar="奄  ━━━━━━━"
  elif [ $volume -gt 14 ]; then
    bar="奄  ━━━━━"
  elif [ $volume -gt 7 ]; then
    bar="奄  ━━━━"
  elif [ $volume -gt 0 ]; then
    bar="奄  ━━"
  else
    bar="奄"
  fi

  # Send the volume indicator notification with dunst
  ~/.config/dunst/dunstify -t 1000 -r 1001 -u low "$bar"
}

case $1 in
  up)
    amixer -D pulse set Master on > /dev/null
    amixer -D pulse sset Master 7%+ > /dev/null

    # Play the freedesktop volume change sound
    play /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga &

    send_notification
  ;;
  down)
    amixer -D pulse set Master on > /dev/null
    amixer -D pulse sset Master 7%- > /dev/null

    # Play the freedesktop volume change sound
    play /usr/share/sounds/freedesktop/stereo/audio-volume-change.oga &

    send_notification
  ;;
  mute)
    amixer -D pulse set Master 1+ toggle > /dev/null
    send_notification
  ;;
esac