#!/bin/bash

function progress_bar {
	character=$1
	amount=$2
	filler=$3
	maxAmount=$4

	string=""

	i=1
	while [ "$i" -le "$maxAmount" ]; do
		if [ "$i" -le "$amount" ]; then
			string=$string$character
		else
			string=$string$filler
		fi
		i=$(($i + 1))
	done

	echo $string
}


function get_volume {
    amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
    amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
	volume=$(get_volume)

	if is_mute ; then
		bar="婢 Mute"
	else
		bar=$(progress_bar █ $(($volume / 3)) " " 30)
	fi

	~/.config/dunst/dunstify -t 1000 -r 1001 -u low "$bar"
}

case $1 in
	up)
		amixer -D pulse set Master on > /dev/null
		amixer -D pulse sset Master 7%+ > /dev/null
		send_notification
	;;
	down)
		amixer -D pulse set Master on > /dev/null
		amixer -D pulse sset Master 7%- > /dev/null
		send_notification
	;;
	mute)
		amixer -D pulse set Master 1+ toggle > /dev/null
		send_notification
	;;
esac